### ISSUE TITLE
Creating orders in database with only one item

### ISSUE THREAD

**Issue by caestrella1** [cestrrada/MovieRental#4]
With the current implementation of `addItemToOrder.php`, each order consists of only one item. Do we want to convert a list of IDs into a string to store in the database and then parse it when a user searches the order details or keep the current functionality?

**Comment by trfoss** [comment]
The way it looks to me, is that all item ids that are in the cart are being added along with the confirmation number. Then ```getItemsFromConfirmation.php```  gets all the item ids with the given confirmationNumber, then natural joins the itemId with the item table to get all the item information.

**Comment by trfoss** [comment]
The conNum is separate from the conId, so we can have multiple instances of the same conNum in our db. I thought I tested everything, and everything was good, but my db is giving me problems again so I have no way to retest right now. I'll let you know as soon as I do.

**Comment by caestrella1** [comment]
Got it, thanks for the explanation!
